### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by DanielSmale** [JoseRivas1998/JSON-Java-Tutorial#1]
Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Unknown Source)
	at java.io.InputStreamReader.<init>(Unknown Source)
	at java.util.Scanner.<init>(Unknown Source)
	at com.tcg.json.JSONUtils.getJSONStringFromFile(JSONUtils.java:13)
	at com.tcg.json.JSONUtils.getJSONObjectFromFile(JSONUtils.java:20)
	at com.tcg.json.Main.main(Main.java:8)

Any ideas on how to solve this. Im pretty sure i followed all the steps

**Comment by JoseRivas1998** [comment]
Can you provide more details please?

**Comment by DanielSmale** [comment]
I followed your tutorial but noticed I had this error. I've downloaded this repo and noticed its here too. Unzip the folder and theres a video of it happening. 
[Error recreation.zip](https://github.com/JoseRivas1998/JSON-Java-Tutorial/files/3973235/Error.recreation.zip)

**Comment by JoseRivas1998** [comment]
Chances are there is something up with your working directory, try changing the path to the file.
